version: 0.2

phases:
  pre_build:
    commands:
            - git clone https://github.com/tjnguyen/demo2.git               
  build:
    commands:
      - mvn install
      
  artifacts:
  files:
    - s3://thu-bucket/artifacts/demo2-0.0.1-SNAPSHOT.war

